name: Weekly Test

on:
  workflow_dispatch: # run on request (no need for PR)
  schedule:
    # every 12AM on Sunday
    - cron: "0 0 * * 0"

jobs:
  Regression-Tests:
    strategy:
      fail-fast: false
      matrix:
        include:
          - toxenv_task: "iseg"
            test_args: "tests/regression/instance_segmentation/test_instance_segmentation.py"
            runs_on: "['self-hosted', 'Linux', 'X64', 'dmount']"
            task: "instance_segmentation"
          - toxenv_task: "iseg_t"
            test_args: "tests/regression/instance_segmentation/test_tiling_instance_segmentation.py"
            runs_on: "['self-hosted', 'Linux', 'X64', 'dmount']"
            task: "instance_segmentation"
          - toxenv_task: "seg"
            test_args: "tests/regression/semantic_segmentation"
            runs_on: "['self-hosted', 'Linux', 'X64', 'dmount']"
            task: "segmentation"
          - toxenv_task: "det"
            test_args: "tests/regression/detection"
            runs_on: "['self-hosted', 'Linux', 'X64', 'dmount']"
            task: "detection"
          - toxenv_task: "ano"
            test_args: "tests/regression/anomaly"
            runs_on: "['self-hosted', 'Linux', 'X64', 'dmount']"
            task: "anomaly"
          - toxenv_task: "act"
            test_args: "tests/regression/action"
            runs_on: "['self-hosted', 'Linux', 'X64', 'dmount']"
            task: "action"
          - toxenv_task: "cls"
            test_args: "tests/regression/classification"
            runs_on: "['self-hosted', 'Linux', 'X64', 'dmount']"
            task: "classification"
    name: Regression-Test-py310-${{ matrix.toxenv_task }}
    uses: ./.github/workflows/run_tests_in_tox.yml
    with:
      python-version: "3.10"
      toxenv-pyver: "py310"
      toxenv-task: ${{ matrix.toxenv_task }}
      test-args: ${{ matrix.test_args }}
      runs-on: ${{ matrix.runs_on }}
      task: ${{ matrix.task }}
      timeout-minutes: 8640
      upload-artifact: true
      artifact-prefix: "weekly-test-results"
